### ISSUE TITLE
[CI] Docker autobuild

### ISSUE THREAD

**Issue by akru** [airalab/robonomics#70]
**Motivation**

Create automation for building docket image and push it into docker hub.

**Comment by akme** [comment]
Github Action: https://github.com/marketplace/actions/build-and-push-docker-images
Base Docker file: https://github.com/airalab/robonomics/blob/master/scripts/docker/Dockerfile

**Comment by akme** [comment]
Here we go:

1. You need to create repo at http://hub.docker.com/ which you need to update in action (I've set it to airalab/robonomics, so the new one could differ)
2. Create Personal Access Token, so we can push images https://hub.docker.com/settings/security
3. Add secrets to GitHub Repo https://github.com/airalab/robonomics/settings/secrets
DOCKER_USERNAME for username
DOCKER_PASSWORD add created PAT here
4. Add action to integration.yml workflow after "Build optimized binary" step
```
    - name: Build and push Docker image
      if: matrix.os == 'ubuntu-latest'
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: airalab/robonomics
        tag_with_ref: true
        tags: latest
        add_git_labels: true
        dockerfile: scripts/docker/Dockerfile
        path: target/release
```
5. After committing changes to workflow, a new push to tag will execute this action, build image, and push to docker hub. New image will be tagged with: latest and v*.*.* tag version.



Everything was tested in my forked repo.
